server:
  port: 80
eureka:
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka  server交互的地址和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #单机就是指向自己

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间，设置等待5000为5秒时间
  ReadTimeout: 2000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 2000

#配置后才会走到熔断里面去
feign:
  hystrix:
    enabled: true

#spring相关配置
spring:
  application:
    name: eurekaConsumer  #服务名